version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: healthcare_navigator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/healthcare_navigator
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sample_prices_ny.csv:/app/sample_prices_ny.csv:ro
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        echo 'Running ETL script...' &&
        poetry run python -m app.etl &&
        echo 'Starting FastAPI application...' &&
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data: 
